# Application Name
spring.application.name=grocery

# Default active profile
#spring.profiles.active=local
spring.datasource.url=jdbc:mysql://host.docker.internal:3307/grocery
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Common JPA
spring.jpa.hibernate.ddl-auto=update

# Security
spring.security.user.name=chaitanya
spring.security.user.password=katash

# JWT
jwt.secret=234#tyej!@453sb$FDEj&!@#782wrd345
jwt.expiration=900000
jwt.issuer=Grocery