# Application Name
spring.application.name=grocery

# Default active profile
spring.profiles.active=local

# Common JPA
spring.jpa.hibernate.ddl-auto=update

# Security
spring.security.user.name=chaitanya
spring.security.user.password=katash

# JWT
jwt.secret=234#tyej!@453sb$FDEj&!@#782wrd345
jwt.expiration=900000
jwt.issuer=Grocery